packages:
  - "client"
  - "server"
allowBuilds:
  "@parcel/watcher": true
  "@prisma/engines": true
  "@scarf/scarf": true
  bcrypt: true
  esbuild: true
  msgpackr-extract: true
  msw: true
  prisma: true
  sharp: true
  unrs-resolver: true
